name = "123nextjsblog"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://blogform.netlify.app/api/content.json"
NEXT_PUBLIC_SITE_URL = "https://nextjs-blog-workers.pages.dev"
NEXT_PUBLIC_SITE_NAME = "Professional Blog"
NEXT_PUBLIC_SITE_DESCRIPTION = "A modern, professional blog built with Next.js"

# Pages configuration for @cloudflare/next-on-pages
pages_build_output_dir = ".vercel/output/static"

# Custom headers for better caching and performance
[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]] 
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=60, s-maxage=120, stale-while-revalidate=300"

# SEO and security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"
Cache-Control = "public, max-age=0, s-maxage=120, stale-while-revalidate=300"