name = "mediumblog123456"
compatibility_date = "2025-01-27"

[vars]
NODE_ENV = "production"

[assets]
directory = "out"
not_found_handling = "single-page-application"

# Custom headers for better caching
[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]] 
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=300"

# SEO and security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"